### ISSUE TITLE
Clean?

### ISSUE THREAD

**Issue by hasanalizxc** [vanhauser-thc/THC-Archive#2]
Hi there,

Hope you are fine. Are they clean or backdoored? And are you member of 5Eyes, 9Eyes and 14Eyes?

Thanks.

**Comment by vanhauser-thc** [comment]
and how would you trust an answer?
the safest bet is to look at the source and/or binary disassembly yourself ...

**Comment by hasanalizxc** [comment]
I am not expert as like you and i asked you directly. And waited from you answer honestly.

**Comment by francisg-gc** [comment]
a better question would be, will there be an archive of "http://wiki.thc.org/" available ?

**Comment by vanhauser-thc** [comment]
@ghost they should all be safe.
@francisg-gc I dont think so - I think the data got lost :(
