### ISSUE TITLE
thcrut 0.1 is still around. 

### ISSUE THREAD

**Issue by dohnuts** [vanhauser-thc/THC-Archive#3]
Y ?

🤪

thcrut-0.1.tar.gz	initial push of all stuff :)	11 months ago
thcrut-1.2.4d.tar.gz	initial push of all stuff :)	11 months ago
thcrut-1.2.4g.tar.gz	initial push of all stuff :)	11 months ago
thcrut-1.2.5.tar.gz	initial push of all stuff :)	11 months ago
thcrut-1.2.tar.gz	initial push of all stuff :)	11 months ago
thcrut.tar.gz

🤪

Me head hurts,
do we need this , 
why you no release clear

Would you please attach a release note or something about those tools to help
the package makers ?

🤪

libnet (1.0 )  is DEAD
please release ?
thcrut with libnet updated ?

🤪

**Comment by vanhauser-thc** [comment]
thcrut v0.1 is there just has a different name: Tools/thc-crut-0.1.tar.gz

most of the tools a very old and serve a historic purpose. so there will be no updates.

currently maintained are only thc-ipv6 and thc-hydra. (and have their own github repostiory)

**Comment by dohnuts** [comment]
ok
